return {
	require('tuque.core.before'),
	require('tuque.core.comment'),
	require('tuque.core.dashboard'),
	require('tuque.core.edgy'),
	require('tuque.core.fidget'),
	require('tuque.core.flash'),
	require('tuque.core.flatten'),
	require('tuque.core.inc-rename'),
	require('tuque.core.mini'),
	-- require('tuque.core.noice'),
	require('tuque.core.nvim-spectre'),
	require('tuque.core.nvim-web-devicons'),
	require('tuque.core.nvim-ufo'),
	-- require('tuque.core.project'),
	require('tuque.core.rainbow-delimiters'),
	-- require('tuque.core.session'),
	require('tuque.core.tasks'),
	require('tuque.core.theme'),
	require('tuque.core.tiny-devicons-auto-colors'),
	require('tuque.core.todo-comments'),
	require('tuque.core.toggleterm'),
	require('tuque.core.treesitter'),
	require('tuque.core.treesj'),
	require('tuque.core.trouble'),

	-- telescope
	require('tuque.telescope.telescope'),
	require('tuque.telescope.fzy'),
	require('tuque.telescope.repo'),
	require('tuque.telescope.smart-open'),
	require('tuque.telescope.zoxide'),
}
