name: "CI"
on:
  push:
    branches:
      - master
  # pull_request:
jobs:
  release:
    strategy:
      matrix:
        system:
          - x86_64-linux
          # - aarch64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run the magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#app-images.${{ matrix.system }}.default --show-trace  --print-build-logs

      - run: cp $(realpath result) tu-${{ matrix.system }}.AppImage

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: nightly
          tag_name: nightly
          prerelease: true
          files: tu*.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
